apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bottany-ingress
spec:
  rules:
    - host: dashboard.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bottany-service
                port:
                  number: 80